name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run tests
      run: |
        pytest
        
    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.ORACLE_SSH_KEY }}
        
    - name: Deploy to Oracle Cloud
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ORACLE_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        rsync -avz --exclude '.git' --exclude 'venv' --exclude '__pycache__' . ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }}:~/job-tracker/
        ssh ${{ secrets.ORACLE_USER }}@${{ secrets.ORACLE_HOST }} "cd ~/job-tracker && bash scripts/deploy.sh"
