name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # Tests are temporarily disabled until the deployment is stable
    # - name: Run tests
    #   run: |
    #     pytest
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ORACLE_SSH_KEY }}
        known_hosts: ${{ secrets.ORACLE_KNOWN_HOSTS }}
        if_key_exists: replace
    
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=accept-new ubuntu@170.9.227.112 "echo SSH connection successful"
      
    - name: Deploy to Oracle Cloud
      run: |
        rsync -avz -e "ssh" --exclude '.git' --exclude 'venv' --exclude '__pycache__' . ubuntu@170.9.227.112:~/job-tracker/
        ssh ubuntu@170.9.227.112 "cd ~/job-tracker && bash scripts/deploy.sh"
