name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    # Tests are temporarily disabled until the deployment is stable
    # - name: Run tests
    #   run: |
    #     pytest
    
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ORACLE_SSH_KEY }}" > ~/.ssh/oci_key
        chmod 600 ~/.ssh/oci_key
        ssh-keyscan 170.9.227.112 >> ~/.ssh/known_hosts
    
    - name: Test SSH connection
      run: |
        ssh -v -i ~/.ssh/oci_key ubuntu@170.9.227.112 "echo SSH connection successful"
      
    - name: Deploy to Oracle Cloud
      run: |
        rsync -avz -e "ssh -i ~/.ssh/oci_key" --exclude '.git' --exclude 'venv' --exclude '__pycache__' . ubuntu@170.9.227.112:~/job-tracker/
        ssh -i ~/.ssh/oci_key ubuntu@170.9.227.112 "cd ~/job-tracker && bash scripts/deploy.sh"
