name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==23.0.1
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    
    - name: Install SSH key using proper action
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DEPLOYMENT_PRIVATE_KEY }}
    
    - name: Add host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t ed25519 170.9.227.112 >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
    
    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@170.9.227.112 "echo SSH connection successful"
      
    - name: Deploy to Oracle Cloud
      if: success()
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude '.git' --exclude 'venv' --exclude '__pycache__' . ubuntu@170.9.227.112:~/job-tracker/
        # Make all scripts executable
        ssh -o StrictHostKeyChecking=no ubuntu@170.9.227.112 "find ~/job-tracker/scripts -name '*.sh' -exec chmod +x {} \;"
        # Try standard deployment first
        ssh -o StrictHostKeyChecking=no ubuntu@170.9.227.112 "cd ~/job-tracker && bash scripts/deploy.sh" || {
          echo "Standard deployment failed, trying fix script..."
          ssh -o StrictHostKeyChecking=no ubuntu@170.9.227.112 "cd ~/job-tracker && bash scripts/fix_deployment.sh"
        }
        ssh -o StrictHostKeyChecking=no ubuntu@170.9.227.112 "chmod +x ~/job-tracker/.git/hooks/post-receive"
